Wave Pirates fix and QoL tweaks
randovania/randomprime pull request #22
Opened 2024-02-13 07:55 UTC by MrMiguel211

Skippable Cutscenes:
- Fixed an issue in Mine Security Station where the wave pirates won't drop down if the player didn't skip the cutscene immediately.

QoL:
- Increased the size of the bottom door open trigger in Root Cave
- Mine Security Station:
  - Changed the Shadow Pirates to activate the Wave Pirates cutscene upon `DeathRattle` instead of `Dead` 
  - Resized the cutscene trigger so it's not accidentaly skipped if jumped over.
  - Removed vanilla behavior of the cutscene playing again upon killing the Shadow Pirates if entering the room in reverse.

2024-02-14 23:50 UTC, Uncle-Reggie commented
I’m not sure I agree with the changes to vanilla behavior in MSS. There are still people who get Storage Depot A and use the cutscene to repo back to where the Wave Pirates are in MSS. I am one of them.

2024-02-14 23:50 UTC, Uncle-Reggie commented
Both triggers are good ideas.

2024-02-16 22:57 UTC, toasterparty commented
what reggie said

2024-02-16 23:13 UTC, duncathan commented
if the qol changes aren't strictly necessary for the fix to work, they should be in a separate PR probably

2024-02-17 04:57 UTC, MrMiguel211 commented
> I’m not sure I agree with the changes to vanilla behavior in MSS. There are still people who get Storage Depot A and use the cutscene to repo back to where the Wave Pirates are in MSS. I am one of them. 

Counterpoints:

1. If you kill the Wave Pirates first then the Shadow Pirates, it would be pretty confusing to see an empty cutscene that replays the music and everything else except that nothing happens.

2. Some people would find it really annoying to be on their way out of the room and kill the shadow pirates for convenience only to be repositioned to the top of the room and need to walk down again.

3. I doubt many other people would care to do speedrun strats in a randomizer but this is just my opinion.

I can still change this if decired.

2024-02-17 14:31 UTC, Uncle-Reggie commented
> > I’m not sure I agree with the changes to vanilla behavior in MSS. There are still people who get Storage Depot A and use the cutscene to repo back to where the Wave Pirates are in MSS. I am one of them.
> 
> Counterpoints:
> 
> 1. If you kill the Wave Pirates first then the Shadow Pirates, it would be pretty confusing to see an empty cutscene that replays the music and everything else except that nothing happens.
> 2. Some people would find it really annoying to be on their way out of the room and kill the shadow pirates for convenience only to be repositioned to the top of the room and need to walk down again.
> 3. I doubt many other people would care to do speedrun strats in a randomizer but this is just my opinion.
> 
> I can still veto this if desired.

Toaster and I had come up with a good grade for the “cost” of a QoL being introduced, and the other MSS changes fall into the “lose more than you gain” category for me. 

The behavior is expected.

2024-02-17 15:54 UTC, Miepee commented
From a casual perspective, these changes are nice, but it'd probably be better to have them seperate from QoL. So that speedrunners who have the muscle memory burned down to use reposition strats can continue to rely on them and newcomers being less confused.

2024-02-17 16:04 UTC, Samuel6710 commented
> If you kill the Wave Pirates first then the Shadow Pirates, it would be pretty confusing to see an empty cutscene that replays the music and everything else except that nothing happens.

> Some people would find it really annoying to be on their way out of the room and kill the shadow pirates for convenience only to be repositioned to the top of the room and need to walk down again.

Are these really valid issues? I genuinely do not see any complaints regarding this vanilla behavior, and many have already been playing with this behavior implemented so they have come to expect it, so reverting this would be counterintuitive because players already expect vanilla behavior out of this. If players understand this behavior fully, they can learn to take advantage of the reposition and make some pretty creative plays in the same way a speedrunner does.

2024-02-18 21:32 UTC, toasterparty requested changes
> Removed vanilla behavior of the cutscene playing again upon killing the Shadow Pirates if entering the room in reverse.

Retract this change. Everything else is good

2024-02-18 21:36 UTC, MrMiguel211 commented
> Retract this change. Everything else is good

I'm still working on some other commits, will probably finish today.

2024-02-18 21:38 UTC, toasterparty commented
Are those commits going into this branch? The less you dogpile into one PR, the faster it is for me to review/approve/merge

2024-02-18 21:40 UTC, MrMiguel211 commented
> Are those commits going into this branch? The less you dogpile into one PR, the faster it is for me to review/approve/merge

mmm I suppose I'll make a different PR then, I still have to change the thing tho

2024-03-08 17:47 UTC, merged