Custom item support
randovania/randomprime pull request #93
Opened 2024-08-04 12:03 UTC by UltiNaruto

Required mains supported for Missiles/PB
Unlimited Missiles/PBs are supported now
Spring Ball has its own item now

2024-08-04 12:05 UTC, UltiNaruto commented
Non required mains seeds need to set unknown1 (which is Unknown Item 2) in starting items to 12 (4 | 8 => Missile Launcher | Power Bomb Launcher).

If you only require mains for missile then it is 8.
If you only require mains for PB then it is 4.

2024-08-08 13:36 UTC, UltiNaruto commented
Migrated Ice Trap from Special Function to Pickup and it doesn't require enable_ice_trap in config anymore

2024-08-13 22:24 UTC, toasterparty requested changes

2024-08-13 22:24 UTC, toasterparty commented on src/pickup_meta.rs
> +		47 => Some(PickupModel::IceTrap),
Why not make ice trap 45?

2024-08-13 22:24 UTC, toasterparty commented on src/pickup_meta.rs
> +
This section was only added because randovania hadn't yet refactored it's pickup database yet. It's no longer needed so I'd prefer to not unnecessarily create aliases for pickup models like this.

2024-08-13 22:24 UTC, toasterparty commented on src/starting_items.rs
> +            unknown1: 12,
What is 12? Can you represent this as an enum value or a bitwise or of enum values:?

2024-08-13 22:24 UTC, toasterparty commented on src/patches.rs
> +                spawn_point.power_suit = 0;
implement this in `starting_items.rs`

2024-08-13 22:24 UTC, toasterparty commented on src/pickup_meta.rs
> +    SpringBall,
You need to handle the case when the caller incorrectly tries to change the `itemMaxCapacity` for these items (see `patch_config.rs`)

2024-08-13 22:24 UTC, toasterparty commented on src/pickup_meta.rs
> +            PickupType::PowerBombLauncher => "Power Bomb Launcher",
I prefer `"Main Power Bomb"`

2024-08-13 22:24 UTC, toasterparty commented on src/patches.rs
> +            b            { new_text_section_end };
While not strictly neccessary, it'd be nice if you could codify this as a property of the `PickupType` definition

2024-08-13 22:24 UTC, toasterparty commented on src/pickup_meta.rs
> +    UnknownItem2, // now used for custom items
Need to do either:

A. If any custom items are used in the program input, throw an error if the user tries to specify `"UnknownItem2"` directly.

or

B. Deprecate usage of UnknownItem2 in the JSON schema

2024-08-13 22:25 UTC, toasterparty commented on src/pickup_meta.rs
> +    UnlimitedMissiles,
These new pickups need to be added to the JSON schema

2024-08-13 22:26 UTC, toasterparty requested changes
Need to update the JSON schema with all of your changes

2024-08-13 22:27 UTC, toasterparty commented
@UltiNaruto PLEASE do not force-push when updating your changes. It makes it hard for me to incrementally review your work (otherwise I have to double over all lines of your code each feedback iteration)

2024-08-13 22:29 UTC, toasterparty commented
Actually, I forgot you may have told me a way to see the old code for force push. It might be fine

2024-08-13 22:30 UTC, toasterparty commented on src/starting_items.rs
> +            unknown1: 12,
EDIT: I see it's both main PBs + missile launcher, I'd still prefer the enum sum for clarity

2024-08-13 22:33 UTC, toasterparty commented
- Fixes #84

2024-08-14 14:27 UTC, UltiNaruto commented on src/pickup_meta.rs
> +		47 => Some(PickupModel::IceTrap),
Isn't it used by nothing?

2024-08-14 14:28 UTC, UltiNaruto commented on src/pickup_meta.rs
> +
Did not know it was not used anymore. A comment that explains that it's not used anymore above the function would have been nice.

2024-08-14 15:10 UTC, UltiNaruto commented on src/pickup_meta.rs
> +    UnknownItem2, // now used for custom items
since it's too complex for me to apply B. I'll go for A then

2024-08-14 22:57 UTC, toasterparty requested changes
So things are less confusing moving forwards, can you rename `unknown0` and `unknown1` in `spawn_point.rs` to `unknown1` and `unknown2`? We should be consistent with where we start count from and I think it's pretty well established we start at 1 when talking about inventory items,

Make sure the JSON input also reflects this change.

2024-08-15 01:42 UTC, UltiNaruto commented
> So things are less confusing moving forwards, can you rename `unknown0` and `unknown1` in `spawn_point.rs` to `unknown1` and `unknown2`? We should be consistent with where we start count from and I think it's pretty well established we start at 1 when talking about inventory items,
> 
> Make sure the JSON input also reflects this change.

`unknown1` or `unknownItem1`?

2024-08-15 02:00 UTC, toasterparty commented
`unknownItem1`

2024-08-15 15:56 UTC, toasterparty requested changes
We're getting close. Thanks for sticking with me

2024-08-15 15:56 UTC, toasterparty commented on schema/randomprime.schema.json
> +                                    "SpringBall"
Did you actually test in-game that the Inventory Activator Special Function works with custom items?

It's fine if it doesn't, but in that case, those pickups wouldn't belong here.

2024-08-15 15:56 UTC, toasterparty commented on schema/randomprime.schema.json
> +                                    "Spring Ball"
Can you put a comment in the `"description"` field for this property to inform the reader that non-vanilla items will use the 2nd unused item slot left in the game?

2024-08-15 15:56 UTC, toasterparty commented on schema/randomprime.schema.json
>                  }
I've decided I don't want the JSON user to have to do any bitwise math. I'd rather we expand our definition of "inventory" to include the custom items, and then do the bitwise math in randomprime when updating game objects.

Feel free to leave `unknownItem2` but it should throw an error if the user uses both. If you're feeling helpful, I'd appreciate it if you could add in `powerSuit` and `unknownItem1` while you're at it (that bit isn't stritcly necessary for this PR, however)

2024-08-15 16:03 UTC, UltiNaruto commented on schema/randomprime.schema.json
> +                                    "SpringBall"
https://github.com/AxioDL/metaforce/blob/main/Runtime/World/CScriptSpecialFunction.cpp#L407C7-L409C8

2024-08-15 16:06 UTC, UltiNaruto commented on schema/randomprime.schema.json
> +                                    "SpringBall"
We're hooking CPlayerState::HasPowerUp() here :
https://github.com/randovania/randomprime/blob/07f32418bd9afdfdc245c7d782c3065705313c82/src/patches.rs#L11545-L11571

2024-08-15 16:45 UTC, toasterparty commented on schema/randomprime.schema.json
> +                                    "SpringBall"
Was a yes or no question

2024-08-15 16:47 UTC, UltiNaruto commented on schema/randomprime.schema.json
> +                                    "SpringBall"
Short answer yes
Long answer since it calls HasPowerUp and it's hooked it should work properly

2024-08-15 16:49 UTC, Miepee commented on schema/randomprime.schema.json
> +                                    "SpringBall"
> it should work properly

it *should* or it *does*?

2024-08-15 16:50 UTC, toasterparty commented on schema/randomprime.schema.json
> +                                    "SpringBall"
When you say stuff like "should" it makes me think you didn't try it out in-game. The question was about whether or not you played the video game with a custom item special function with words like `actually` for emphasis.

2024-08-15 16:53 UTC, UltiNaruto commented on schema/randomprime.schema.json
> +                                    "SpringBall"
I haven't tested Inventory Activator but if you read the code. It's pretty much self explanatory that it will work as intended considering HasPowerUp returns what it's supposed to return.

HasPowerUp correctly returns true when you have the custom item so it will function properly.

2024-08-17 15:43 UTC, toasterparty requested changes
I just noticed `game_config.spring_ball_item` isn't in the JSON schema. Can you please add that and then make it so that it defaults to the spring ball item if unspecified and `game_config.spring_ball == false`?

Also, placing a spring ball pickup while `game_config.spring_ball == false` doesn't do anything which is a little confusing. I think we should have the patcher panic if the user tries to place spring ball while spring ball is disabled

2024-08-17 15:43 UTC, toasterparty commented on schema/randomprime.schema.json
> +                },
These should be `"default": true`

2024-08-17 15:54 UTC, toasterparty commented
Actually, @UltiNaruto we should deprecated `game_config.spring_ball` and default `game_config.spring_ball_item` to the custom pickup.

Sorry for the flip flop, caffine still kicking in

2024-08-17 15:58 UTC, duncathan commented
> Actually, @UltiNaruto we should deprecated `game_config.spring_ball` and default `game_config.spring_ball_item` to the custom pickup.
> 
> Sorry for the flip flop, caffine still kicking in

Would it perhaps be preferable to default it to bombs, for backwards compatibility?

2024-08-17 16:32 UTC, toasterparty commented
To preserve backwards compatibility, make it so that `springBall: true` sets `springBallItem: Bombs`.

2024-08-17 19:38 UTC, UltiNaruto commented
I thought about another idea. What about making `springBall` default to `false` and if it's set to `true` with a pickup having `SpringBall` as its type then it complains about both being used?

`springBall` would remain useable and not deprecated but using both makes the patcher panic with the following message `Use either springBall or add a pickup as SpringBall type`

As for using `SpringBall` type for pickups, it would detect it then change `springBall` to `true` and `springBallItem` to `SpringBall`.

2024-08-19 20:12 UTC, toasterparty commented
@UltiNaruto I really think this is the best option, please implement it:

1. Deprecate `springBall` in the JSON schema and remove all `if config.spring_ball` conditions
2. Add `springBallItem` to the JSON schema with `"default": "Spring Ball"`
3. Add the following

```rs
let spring_ball_item = match spring_ball_item {
    Some(spring_ball_item) => spring_ball_item,
    None => {
        match spring_ball {
            false => "Spring Ball",
            true => "Morph Ball Bombs",
        }
    },
}
```

2024-08-20 02:50 UTC, UltiNaruto commented
Up to you. I'll do that then.

2024-08-24 15:44 UTC, toasterparty requested changes
I'm pretty happy with the code but in my testing `startingItems` isn't working. Please check using this JSON file which should start with all the custom items.

```rs
{
    "$schema": "./schema/randomprime.schema.json",
    "gameConfig": {
        "startingRoom": "Tallon Overworld:Arbor Chamber",
        "startingItems": {
            "combatVisor": true,
            "powerBeam": true,
            "scanVisor": true,
            "missiles": 10,
            "energyTanks": 0,
            "powerBombs": 8,
            "wave": false,
            "ice": false,
            "plasma": false,
            "charge": false,
            "morphBall": true,
            "bombs": false,
            "spiderBall": false,
            "boostBall": false,
            "powerSuit": 0,
            "variaSuit": false,
            "gravitySuit": false,
            "phazonSuit": false,
            "thermalVisor": false,
            "xray": false,
            "spaceJump": true,
            "grapple": false,
            "superMissile": false,
            "wavebuster": false,
            "iceSpreader": false,
            "flamethrower": false,
            "unknownItem1": 0,
            "unlimitedMissiles": true,
            "unlimitedPowerBombs": true,
            "missileLauncher": true,
            "powerBombLauncher": true,
            "springBall": true
        }
    },
    "levelData": {
        "Tallon Overworld": {
            "rooms": {
                "Arbor Chamber": {
                    "pickups": [
                        {
                            "type": "Spring Ball"
                        },
                        {
                            "type": "Main Power Bomb",
                            "position": [-723.6977, 334.1136, 40.2428]
                        },
                        {
                            "type": "Missile Launcher",
                            "position": [-723.6977, 329.1136, 40.2428]
                        },
                        {
                            "type": "Unlimited Missiles",
                            "position": [-723.6977, 344.1136, 40.2428]
                        },
                        {
                            "type": "Unlimited Power Bombs",
                            "position": [-723.6977, 349.1136, 40.2428]
                        }
                    ]
                }
            }
        }
    }
}
```

Also, please update use the struct to define starting items rather than `u64` so that the player spawns with missile/pb launcher if left unspecified

```rs
let starting_items = {
    let items = self.game_config.starting_items.as_ref();

    match items {
        Some(items) => items.clone(),
        None => {
            if force_vanilla_layout {
                StartingItems::from_u64(2188378143)
            } else {
                StartingItems::from_u64(1)
            }
        }
    }
};
```

2024-08-24 15:44 UTC, toasterparty commented on schema/randomprime.schema.json
> +                                    "Spring Ball"
bump

2024-08-24 17:40 UTC, UltiNaruto commented
> I'm pretty happy with the code but in my testing `startingItems` isn't working. Please check using this JSON file which should start with all the custom items.
> 
> ```rust
> {
>     "$schema": "./schema/randomprime.schema.json",
>     "gameConfig": {
>         "startingRoom": "Tallon Overworld:Arbor Chamber",
>         "startingItems": {
>             "combatVisor": true,
>             "powerBeam": true,
>             "scanVisor": true,
>             "missiles": 10,
>             "energyTanks": 0,
>             "powerBombs": 8,
>             "wave": false,
>             "ice": false,
>             "plasma": false,
>             "charge": false,
>             "morphBall": true,
>             "bombs": false,
>             "spiderBall": false,
>             "boostBall": false,
>             "powerSuit": 0,
>             "variaSuit": false,
>             "gravitySuit": false,
>             "phazonSuit": false,
>             "thermalVisor": false,
>             "xray": false,
>             "spaceJump": true,
>             "grapple": false,
>             "superMissile": false,
>             "wavebuster": false,
>             "iceSpreader": false,
>             "flamethrower": false,
>             "unknownItem1": 0,
>             "unlimitedMissiles": true,
>             "unlimitedPowerBombs": true,
>             "missileLauncher": true,
>             "powerBombLauncher": true,
>             "springBall": true
>         }
>     },
>     "levelData": {
>         "Tallon Overworld": {
>             "rooms": {
>                 "Arbor Chamber": {
>                     "pickups": [
>                         {
>                             "type": "Spring Ball"
>                         },
>                         {
>                             "type": "Main Power Bomb",
>                             "position": [-723.6977, 334.1136, 40.2428]
>                         },
>                         {
>                             "type": "Missile Launcher",
>                             "position": [-723.6977, 329.1136, 40.2428]
>                         },
>                         {
>                             "type": "Unlimited Missiles",
>                             "position": [-723.6977, 344.1136, 40.2428]
>                         },
>                         {
>                             "type": "Unlimited Power Bombs",
>                             "position": [-723.6977, 349.1136, 40.2428]
>                         }
>                     ]
>                 }
>             }
>         }
>     }
> }
> ```
> 
> Also, please update use the struct to define starting items rather than `u64` so that the player spawns with missile/pb launcher if left unspecified
> 
> ```rust
> let starting_items = {
>     let items = self.game_config.starting_items.as_ref();
> 
>     match items {
>         Some(items) => items.clone(),
>         None => {
>             if force_vanilla_layout {
>                 StartingItems::from_u64(2188378143)
>             } else {
>                 StartingItems::from_u64(1)
>             }
>         }
>     }
> };
> ```

don't forget to add item max capacity 2^31 else unknown item 2 cannot be set since it defaults to 0 max

```json
{
    "$schema": "./schema/randomprime.schema.json",
    "gameConfig": {
        "startingRoom": "Tallon Overworld:Arbor Chamber",
        "startingItems": {
            "combatVisor": true,
            "powerBeam": true,
            "scanVisor": true,
            "missiles": 10,
            "energyTanks": 0,
            "powerBombs": 8,
            "wave": false,
            "ice": false,
            "plasma": false,
            "charge": false,
            "morphBall": true,
            "bombs": false,
            "spiderBall": false,
            "boostBall": false,
            "powerSuit": 0,
            "variaSuit": false,
            "gravitySuit": false,
            "phazonSuit": false,
            "thermalVisor": false,
            "xray": false,
            "spaceJump": true,
            "grapple": false,
            "superMissile": false,
            "wavebuster": false,
            "iceSpreader": false,
            "flamethrower": false,
            "unknownItem1": 0,
            "unlimitedMissiles": true,
            "unlimitedPowerBombs": true,
            "missileLauncher": true,
            "powerBombLauncher": true,
            "springBall": true
        },
        "itemMaxCapacity": {
            "Unknown Item 2": 2147483647
        }
    },
    "levelData": {
        "Tallon Overworld": {
            "rooms": {
                "Arbor Chamber": {
                    "pickups": [
                        {
                            "type": "Spring Ball"
                        },
                        {
                            "type": "Main Power Bomb",
                            "position": [-723.6977, 334.1136, 40.2428]
                        },
                        {
                            "type": "Missile Launcher",
                            "position": [-723.6977, 329.1136, 40.2428]
                        },
                        {
                            "type": "Unlimited Missiles",
                            "position": [-723.6977, 344.1136, 40.2428]
                        },
                        {
                            "type": "Unlimited Power Bombs",
                            "position": [-723.6977, 349.1136, 40.2428]
                        }
                    ]
                }
            }
        }
    }
}```

2024-08-24 17:49 UTC, toasterparty commented
@UltiNaruto the default max capacity for unknown2 should change then because that was really unintuitive

2024-08-24 17:52 UTC, UltiNaruto commented
fixed the starting custom item issue

2024-08-24 17:53 UTC, UltiNaruto commented
> @UltiNaruto the default max capacity for unknown2 should change then because that was really unintuitive

Defaults to 1 in the schema

2024-08-24 17:55 UTC, UltiNaruto commented
Do we want just to change the schema or add unknown item 2 if it's not specified in patch_config.rs?

2024-08-24 17:56 UTC, toasterparty commented
We'll need to always patch unknown_item_2 regardless if it's in the JSON or not.

I'm defining "backwards compatible" here as "not fundamentally changing the behavior of explicitly named JSON properties". That means changing the default value used for an unspecified property is a non-breaking change.

2024-08-24 19:06 UTC, UltiNaruto commented
now the patch config will auto add Unknown Item 2 with the correct value if it's not specified.
also I fixed the negative capacity patch for custom items which will properly remove the custom item.

2024-08-26 19:41 UTC, toasterparty requested changes

2024-08-26 19:41 UTC, toasterparty commented on schema/randomprime.schema.json
> +                    "default": "Spring Ball"
This needs to be an enum of all accepted values. What you probably should do is move the enum definition from `pickups.type` to `$defs` and reference (i.e. `"$ref"`) it from both places it needs to be used.

2024-08-30 03:12 UTC, toasterparty requested changes

2024-08-30 03:12 UTC, toasterparty commented on schema/randomprime.schema.json
>                  },
```suggestion
                "springBallItem": {
                    "description": "Spring Ball will require this item to be obtained before being able to use it.",
                    "$ref": "#/$defs/pickupType",
                    "not": {
                        "enum": [
                            "Nothing",
                            "Floaty Jump",
                            "Ice Trap"
                        ]
                    }
                },
```

2024-08-30 03:12 UTC, toasterparty commented on schema/randomprime.schema.json
> +                                "$ref": "#/$defs/pickupType",
Following your new JSON schema, an inventory activator special function would be:

```json
                    "specialFunctions": [
                        {
                            "id": 9000002,
                            "type": "InventoryActivator",
                            "itemId": "Missile Launcher"
                        }
                    ],
```

but that's invalid input:

```
error: JSON parse failed: unknown variant `Missile Launcher`, expected one of `PowerBeam`, `IceBeam`, `WaveBeam`, `PlasmaBeam`, `Missile`, `ScanVisor`, `MorphBallBomb`, `PowerBomb`, `Flamethrower`, `ThermalVisor`, `ChargeBeam`, `SuperMissile`, `GrappleBeam`, `XRayVisor`, `IceSpreader`, `SpaceJumpBoots`, `MorphBall`, `CombatVisor`, `BoostBall`, `SpiderBall`, `PowerSuit`, `GravitySuit`, `VariaSuit`, `PhazonSuit`, `EnergyTank`, `UnknownItem1`, `HealthRefill`, `UnknownItem2`, `Wavebuster`, `ArtifactOfTruth`, `ArtifactOfStrength`, `ArtifactOfElder`, `ArtifactOfWild`, `ArtifactOfLifegiver`, `ArtifactOfWarrior`, `ArtifactOfChozo`, `ArtifactOfNature`, `ArtifactOfSun`, `ArtifactOfWorld`, `ArtifactOfSpirit`, `ArtifactOfNewborn`, `UnlimitedMissiles`, `UnlimitedPowerBombs`, `MissileLauncher`, `PowerBombLauncher`, `SpringBall`, `Nothing`, `FloatyJump`, `IceTrap` at line 86 column 56
```

Easiest fix here is to add `replace(" ", "")` to `PickupType::from_str` and use that instead of `PickupType` directly.

You can blame me for making this inconsistent in the first place. Your new JSON schema should be what we use going forwards.

2024-08-30 12:41 UTC, UltiNaruto commented on schema/randomprime.schema.json
>                  },
completely forgot this one

2024-08-30 12:49 UTC, UltiNaruto commented on schema/randomprime.schema.json
> +                                "$ref": "#/$defs/pickupType",
PickupType::from_str() already uses the whitespace variant

2024-09-01 02:15 UTC, toasterparty requested changes
I found a bug with the `InventoryActivator` special function. It appears that *any* custom pickup will meet the activation requirement, not just the item id named in the special function object.

Here's an example where the path through Waterfall Cavern is supposed to be blocked until the player has `"Missile Launcher"` in their inventory, yet it allows the player through with only `"Main Power Bomb"`:

```json
{
    "$schema": "./schema/randomprime.schema.json",
    "gameConfig": {
        "startingRoom": "Tallon Overworld:Waterfall Cavern",
        "startingItems": {
            "combatVisor": true,
            "powerBeam": true,
            "scanVisor": true,
            "missiles": 10,
            "energyTanks": 0,
            "powerBombs": 3,
            "wave": false,
            "ice": false,
            "plasma": false,
            "charge": false,
            "morphBall": true,
            "bombs": false,
            "spiderBall": false,
            "boostBall": false,
            "powerSuit": 0,
            "variaSuit": false,
            "gravitySuit": false,
            "phazonSuit": false,
            "thermalVisor": false,
            "xray": false,
            "spaceJump": true,
            "grapple": false,
            "superMissile": false,
            "wavebuster": false,
            "iceSpreader": false,
            "flamethrower": false,
            "unknownItem1": 0,
            "unlimitedMissiles": false,
            "unlimitedPowerBombs": false,
            "missileLauncher": false,
            "powerBombLauncher": false,
            "springBall": false
        }
    },
    "levelData": {
        "Tallon Overworld": {
            "rooms": {
                "Waterfall Cavern": {
                    "pickups": [
                        {
                            "type": "Main Power Bomb",
                            "position": [-257.8459, 434.5406, -36.1156]
                        }
                    ],
                    "blocks": [
                        {
                            "id": 9000000,
                            "position": [-269.5781, 445.1988, -43.7749],
                            "scale": [10.0, 2.0, 5.0]
                        }
                    ],
                    "triggers": [
                        {
                            "id": 9000001,
                            "position": [-269.5781, 445.1988, -43.7749],
                            "scale": [15.0, 15.0, 30.0]
                        }
                    ],
                    "specialFunctions": [
                        {
                            "id": 9000002,
                            "type": "InventoryActivator",
                            "itemId": "Missile Launcher"
                        }
                    ],
                    "addConnections": [
                        {
                            "senderId": 9000001,
                            "state": "INSIDE",
                            "targetId": 9000002,
                            "message": "ACTION"
                        },
                        {
                            "senderId": 9000002,
                            "state": "ZERO",
                            "targetId": 9000000,
                            "message": "DEACTIVATE"
                        }
                    ]
                }
            }
        }
    }
}
```

If the fix for this isn't trivial, that's fine, we'll just remove the custom pickups from the special function `itemId` enum and move on.

2024-09-01 15:36 UTC, UltiNaruto commented
Fixed it. It was just missing a value & 1 to prevent the value to be higher than 1.

2024-09-16 14:47 UTC, toasterparty requested changes
Please make the Missile Launcher default to +5 missile capacity instead of +1

2024-09-16 15:04 UTC, Miepee commented on src/patches.rs
> +    // TODO: Fix it for PAL
As someone who's not able to read PPC ASM, what exactly is broken/different on PAL here?

2024-09-16 15:25 UTC, UltiNaruto commented on src/patches.rs
> +    // TODO: Fix it for PAL
oh I forgot to remove this comment since it's fixed

2024-09-16 15:27 UTC, UltiNaruto commented on src/patches.rs
> +    // TODO: Fix it for PAL
What was broken is that some registers were used on PAL while it was unused on non PAL. I used some other registers that weren't used in each version.

2024-09-16 16:04 UTC, toasterparty requested changes

2024-09-16 16:04 UTC, toasterparty commented on src/patches.rs
> +            b            end_init_power_up;
This needs to account for if the player is already underwater. The way you have implemented it has several problems:

- if you receive floaty jump while underwater, the distance underwater is ruined making it harder to jump out of water without gravity suit
- if you receive floaty jump while underwater, your fluid count is set to 1 instead of 2, meaning you can't re-activate floaty by leaving a water box through it's side
- if you remove floaty jump while underwater, it incorrectly gives the player "psuedo-grav" properties


Note that there is also some places in vanilla where it is acceptable to have fluid count of 2 (crashed frigate).

2024-09-17 15:01 UTC, UltiNaruto commented on src/patches.rs
> +            b            end_init_power_up;
if adding floaty jump :
- if out of water ticks not 2 then jump to end_init_power_up
- else set fluid count to 1 and fluid depth to 20.0
else:
- if out of water ticks not 2 then jump to end_init_power_up
- else set fluid count to 0

would it be good like that?

2024-09-17 15:06 UTC, toasterparty commented on src/patches.rs
> +            b            end_init_power_up;
What is out of water ticks? The number of frames the player is not submerged?

2024-09-17 15:10 UTC, UltiNaruto commented on src/patches.rs
> +            b            end_init_power_up;
Most likely. It's checked a lot when parsing surface restraint and always checks against 2 which is fully out of water.

2024-09-17 15:13 UTC, UltiNaruto commented on src/patches.rs
> +            b            end_init_power_up;
That's the check that is often used that I mentioned above : https://github.com/AxioDL/metaforce/blob/main/Runtime/World/CPlayer.hpp#L599-L601

2024-09-17 15:19 UTC, toasterparty commented on src/patches.rs
> +            b            end_init_power_up;
```
fn give_floaty:
    fluid_count += 1

    if out_of_water_ticks >= 2:
        fluid_depth = 20.0f

fn remove_floaty:
    if fluid_count > 0:
        fluid_count -= 1

    if out_of_water_ticks >= 2:
        fluid_depth = 0.0f
```

2024-09-17 15:23 UTC, toasterparty commented on src/patches.rs
> +            b            end_init_power_up;
Your discretion whether the `>=` is necessary or if  `==` is sufficient

2024-09-17 15:24 UTC, UltiNaruto commented on src/patches.rs
> +            b            end_init_power_up;
the GetSurfaceRestraint() function clearly says `==` so I'm going to follow what that function is doing

2024-09-17 15:59 UTC, UltiNaruto commented on src/patches.rs
> +            b            end_init_power_up;
```
check_floaty_jump:
            cmpwi        r29, { PickupType::FloatyJump.kind() };
            bne          continue_init_power_up;
            lwz          r3, 0x84c(r30);
            lwz          r5, { actor_flags_offset }(r3);
            srwi         r5, r5, 12; // remove bits on the right of fluid count
            andi         r5, r5, 7;  // remove bits on the left of fluid count
            cmpwi        r14, 0;
            blt          remove_floaty_jump;
            slwi         r5, r5, 1;  // move current fluid count to next bit
            ori          r5, r5, 1;  // add 1 to current fluid count
            andi         r5, r5, 7;  // making sure we don't go past 7 (=> 0b111)
            slwi         r5, r5, 12;
            or           r4, r4, r5; // actor flags |= (value << 12)
            lwz          r3, { out_of_water_ticks_offset }(r30);
            cmpwi        r3, 2;      // check if we are in water
            bne          apply_underwater_floaty_jump;
            lis          r5, 0x41a0; // 20.0
            b            apply_floaty_jump;
        remove_floaty_jump:
            srwi         r5, r5, 1;  // move current fluid count to previous
            nor          r5, r5, r5; // flip bits
            andi         r5, r5, 7;  // making sure we don't go past 7 (=> 0b111)
            slwi         r5, r5, 12;
            and          r4, r4, r5; // actor flags &= (((~value) & 7) << 12)
            cmpwi        r3, 2;      // check if we are in water
            bne          apply_underwater_floaty_jump;
            lis          r5, 0;
        apply_floaty_jump:
            stw          r4, { actor_flags_offset }(r3);
        apply_underwater_floaty_jump:
            stw          r5, { fluid_depth_offset }(r3);
            b            end_init_power_up;
```

2024-09-19 21:08 UTC, toasterparty commented on src/add_modify_obj_patches.rs
> +    let item_id = PickupType::from_str(&item_id[..]) as u32;
Why was this necessary? Why switch to `item_id: Option<String>` from `Option<PickupType>`?

2024-09-24 12:56 UTC, UltiNaruto commented on src/patches.rs
> +            b            end_init_power_up;
this still needs confirmation that this is what you want

2024-09-24 12:57 UTC, UltiNaruto commented on src/add_modify_obj_patches.rs
> +    let item_id = PickupType::from_str(&item_id[..]) as u32;
I think there was an issue with it at the beginning. I can try to restore it to what it was and see if there's still a problem with it.

2024-09-24 13:01 UTC, UltiNaruto commented on src/add_modify_obj_patches.rs
> +    let item_id = PickupType::from_str(&item_id[..]) as u32;
Ok I found it back. https://github.com/randovania/randomprime/pull/93#discussion_r1737790870

2024-09-24 16:20 UTC, toasterparty commented on src/add_modify_obj_patches.rs
> +    let item_id = PickupType::from_str(&item_id[..]) as u32;
In that case, something like this would be more appropriate:

```rs
let pickup_type = match config.item_id.as_ref() {
    Some(item_id) => {
        PickupType::from_str(item_id)
    },
    None => {
        PickupType::PowerBeam
    },
};
let item_id = pickup_type as u32;
```

2024-09-24 16:31 UTC, toasterparty commented on src/patches.rs
> +            b            end_init_power_up;
Here's my test JSON. The underwater depth count seems correct, but we're still not getting the correct fluid count. If you collect the "Remove Floaty Jump" under the water, you should not get "psuedo-grav". If you collect the floaty jump under the water and then leave the water, you should still have a non-zero fluid count.

```json
{
    "$schema": "./schema/randomprime.schema.json",
    "gameConfig": {
        "startingRoom": "Tallon Overworld:Landing Site",
        "startingItems": {
            "combatVisor": true,
            "powerBeam": true,
            "scanVisor": true,
            "missiles": 10,
            "energyTanks": 0,
            "powerBombs": 3,
            "wave": false,
            "ice": false,
            "plasma": false,
            "charge": false,
            "morphBall": true,
            "bombs": false,
            "spiderBall": false,
            "boostBall": false,
            "powerSuit": 0,
            "variaSuit": false,
            "gravitySuit": false,
            "phazonSuit": false,
            "thermalVisor": false,
            "xray": false,
            "spaceJump": true,
            "grapple": false,
            "superMissile": false,
            "wavebuster": false,
            "iceSpreader": false,
            "flamethrower": false,
            "unknownItem1": 0,
            "unlimitedMissiles": false,
            "unlimitedPowerBombs": false,
            "missileLauncher": false,
            "powerBombLauncher": false,
            "springBall": false
        }
    },
    "levelData": {
        "Tallon Overworld": {
            "rooms": {
                "Landing Site": {
                    "pickups": [
                        {
                            "type": "Floaty Jump",
                            "position": [-369.6311, 374.9892, -20.7154]
                        },
                        {
                            "type": "Floaty Jump",
                            "scanText": "Remove Floaty Jump",
                            "maxIncrease": -1,
                            "position": [-369.6311, 360.9892, -20.7154]
                        },
                        {
                            "type": "Floaty Jump",
                            "position": [-334.3455, 319.7977, -39.3822]
                        },
                        {
                            "type": "Floaty Jump",
                            "scanText": "Remove Floaty Jump",
                            "maxIncrease": -1,
                            "position": [-334.3455, 311.7977, -39.3822]
                        }
                    ]
                }
            }
        }
    }
}
```

2024-09-24 16:32 UTC, toasterparty requested changes
- Fix FJ implementation or back the changes out
- Implement default item id for special functions without using a string literal

2024-09-25 03:03 UTC, UltiNaruto commented on src/patches.rs
> +            b            end_init_power_up;
should work with this code now :

```
// check if it is floaty jump
        check_floaty_jump:
            cmpwi        r29, { PickupType::FloatyJump.kind() };
            bne          continue_init_power_up;
            lwz          r3, 0x84c(r30);
            lwz          r0, { out_of_water_ticks_offset }(r3);
            lwz          r5, { actor_flags_offset }(r3);
            mr           r4, r5;
            srwi         r5, r5, 14; // remove bits on the right of fluid count
            andi         r5, r5, 7;  // remove bits on the left of fluid count

            // remove fluid counts
            lis          r6, 0xffff;
            ori          r6, r6, 0x3fff;
            and          r4, r4, r6;

            cmpwi        r14, 0;
            blt          remove_floaty_jump;
            addi         r5, r5, 1;  // add 1 to fluid count
            andi         r5, r5, 7;  // making sure we don't go past 3 bits (=> 0b111)
            slwi         r5, r5, 14;
            or           r4, r4, r5; // actor flags |= (value << 14)
            cmpwi        r0, 2;      // check if we are in water
            bne          apply_underwater_floaty_jump;
            lis          r5, 0x41a0; // 20.0
            b            apply_floaty_jump;
        remove_floaty_jump:
            cmpwi        r5, 0;
            ble          do_not_decrement_fluid_count;
            addi         r5, r5, -1; // subtract 1 to fluid count
        do_not_decrement_fluid_count:
            andi         r5, r5, 7;  // making sure we don't go past 3 bits (=> 0b111)
            slwi         r5, r5, 14;
            or           r4, r4, r5; // actor flags |= (value << 14)
            cmpwi        r0, 2;      // check if we are in water
            bne          apply_underwater_floaty_jump;
            lis          r5, 0;
        apply_floaty_jump:
            stw          r5, { fluid_depth_offset }(r3);
        apply_underwater_floaty_jump:
            stw          r4, { actor_flags_offset }(r3);
            b            end_init_power_up;```

2024-10-05 11:03 UTC, UltiNaruto commented on src/patches.rs
> +            b            end_init_power_up;
this still needs confirmation that this is what you want

2024-10-05 14:56 UTC, toasterparty commented on src/patches.rs
> +            b            end_init_power_up;
I thought I made it very clear what conditions need to be met and even went to the lengths of providing you with test JSON that can be used to validate those conditions:

> If you collect the "Remove Floaty Jump" under the water, you should not get "psuedo-grav". If you collect the floaty jump under the water and then leave the water, you should still have a non-zero fluid count.

It's not my responsibility to test your changes. Push your changes if you think they are ready and I will review, otherwise test it yourself if you're not sure.

2024-10-09 18:12 UTC, toasterparty requested changes
![image](https://github.com/user-attachments/assets/fc091b18-071b-4d8a-a884-11f3c97a46e2)

Collect this item as the first and only item. After acquisition, the player must not have full influence underwater (i.e. they must not be able to move as if they have gravity suit without actually having gravity suit)

2024-10-13 12:59 UTC, UltiNaruto commented
Well nvm it wasn't recompiled to latest version. I'll add a out of water ticks check to fluid count decrement.

2024-10-19 22:27 UTC, toasterparty approved these changes

2024-10-19 22:27 UTC, merged